from enum import IntFlag
from typing import NamedTuple

class flags(IntFlag):
    CREATE = ...
    DELETE = ...
    MODIFY = ...
    MOVED_FROM = ...
    MOVED_TO = ...
    CLOSE_WRITE = ...
    ATTRIB = ...

    @staticmethod
    def from_mask(mask: int) -> list[flags]: ...

class Event(NamedTuple):
    wd: int
    mask: int
    cookie: int
    name: str

class INotify:
    def __init__(self, inheritable: bool = ...) -> None: ...
    def add_watch(self, path: str, mask: int) -> int: ...
    def read(self, timeout: int | None = ..., read_delay: int | None = ...) -> list[Event]: ...
