# Generated by tools/generate_protocol_models.py; do not edit.
from __future__ import annotations

from typing import Final, Literal, NotRequired, TypedDict

PROTOCOL_VERSION: Final = 'kirocrew-agentcore.v1'
CLIENT_OPERATIONS: Final = frozenset(['connection.hello', 'chat.submit', 'chat.cancel', 'kiro.login.start', 'kiro.status', 'kiro.logout', 'kirocrew.ws.send', 'kirocrew.ws.close', 'sandbox.prepare_stop', 'ping'])
SERVER_OPERATIONS: Final = frozenset(['connection.ready', 'sandbox.state', 'kiro.auth_status', 'kiro.auth_required', 'kiro.authenticated', 'request.accepted', 'output.delta', 'tool.activity', 'artifact.created', 'request.completed', 'checkpoint.committed', 'error', 'pong'])
ERROR_CODES: Final = frozenset(['INVALID_MESSAGE', 'UNSUPPORTED_PROTOCOL', 'FRAME_TOO_LARGE', 'SEQUENCE_ERROR', 'IDEMPOTENCY_CONFLICT', 'AUTHENTICATION_FAILED', 'AUTHORIZATION_FAILED', 'BINDING_MISMATCH', 'SANDBOX_CONFLICT', 'CHECKPOINT_FAILED', 'PERSISTENCE_RESTORE_FAILED', 'KIRO_AUTH_REQUIRED', 'KIROCREW_UNAVAILABLE', 'FEATURE_UNAVAILABLE_IN_AGENTCORE', 'THROTTLED', 'INTERNAL_ERROR'])
ERROR_CATEGORIES: Final = frozenset(['AUTHENTICATION', 'AUTHORIZATION', 'BINDING', 'LIFECYCLE', 'PROVISIONING', 'TRANSPORT', 'KIRO_AUTH', 'KIROCREW', 'PERSISTENCE', 'THROTTLING', 'INTERNAL'])

ClientOperation = Literal["connection.hello", "chat.submit", "chat.cancel", "kiro.login.start", "kiro.status", "kiro.logout", "kirocrew.ws.send", "kirocrew.ws.close", "sandbox.prepare_stop", "ping"]
ServerOperation = Literal["connection.ready", "sandbox.state", "kiro.auth_status", "kiro.auth_required", "kiro.authenticated", "request.accepted", "output.delta", "tool.activity", "artifact.created", "request.completed", "checkpoint.committed", "error", "pong"]
Operation = ClientOperation | ServerOperation
ErrorCode = Literal["INVALID_MESSAGE", "UNSUPPORTED_PROTOCOL", "FRAME_TOO_LARGE", "SEQUENCE_ERROR", "IDEMPOTENCY_CONFLICT", "AUTHENTICATION_FAILED", "AUTHORIZATION_FAILED", "BINDING_MISMATCH", "SANDBOX_CONFLICT", "CHECKPOINT_FAILED", "PERSISTENCE_RESTORE_FAILED", "KIRO_AUTH_REQUIRED", "KIROCREW_UNAVAILABLE", "FEATURE_UNAVAILABLE_IN_AGENTCORE", "THROTTLED", "INTERNAL_ERROR"]
ErrorCategory = Literal["AUTHENTICATION", "AUTHORIZATION", "BINDING", "LIFECYCLE", "PROVISIONING", "TRANSPORT", "KIRO_AUTH", "KIROCREW", "PERSISTENCE", "THROTTLING", "INTERNAL"]


class ProtocolEnvelope(TypedDict):
    version: Literal["kirocrew-agentcore.v1"]
    messageId: str
    requestId: NotRequired[str | None]
    operation: Operation
    sequence: int
    timestamp: str
    correlationId: str
    payload: dict[str, object]


class ProtocolError(TypedDict):
    code: ErrorCode
    category: ErrorCategory
    message: str
    retryable: bool
    correlationId: str
    details: NotRequired[dict[str, str | int | float | bool | None]]
