from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "contracts/schemas"
PYTHON_OUTPUT = ROOT / "adapter/src/kirocrew_agentcore_adapter/generated_protocol.py"
TYPESCRIPT_OUTPUT = ROOT / "frontend-shell/src/generated/protocol.ts"
PACKAGED_SCHEMA_DIR = ROOT / "adapter/src/kirocrew_agentcore_adapter/schemas"
SCHEMA_NAMES = (
    "protocol-envelope.schema.json",
    "http-invocation.schema.json",
    "error.schema.json",
)


def load_schema(name: str) -> dict[str, Any]:
    return cast(
        dict[str, Any],
        json.loads((SCHEMA_DIR / name).read_text(encoding="utf-8")),
    )


def quoted_union(values: list[str], separator: str) -> str:
    return separator.join(json.dumps(value) for value in values)


def generated_contents() -> tuple[str, str]:
    envelope = load_schema("protocol-envelope.schema.json")
    error = load_schema("error.schema.json")
    version = cast(str, envelope["properties"]["version"]["const"])
    client_operations = cast(list[str], envelope["$defs"]["clientOperation"]["enum"])
    server_operations = cast(list[str], envelope["$defs"]["serverOperation"]["enum"])
    error_codes = cast(list[str], error["properties"]["code"]["enum"])
    error_categories = cast(list[str], error["properties"]["category"]["enum"])

    python = f'''# Generated by tools/generate_protocol_models.py; do not edit.
from __future__ import annotations

from typing import Final, Literal, NotRequired, TypedDict

PROTOCOL_VERSION: Final = {version!r}
CLIENT_OPERATIONS: Final = frozenset({client_operations!r})
SERVER_OPERATIONS: Final = frozenset({server_operations!r})
ERROR_CODES: Final = frozenset({error_codes!r})
ERROR_CATEGORIES: Final = frozenset({error_categories!r})

ClientOperation = Literal[{quoted_union(client_operations, ", ")}]
ServerOperation = Literal[{quoted_union(server_operations, ", ")}]
Operation = ClientOperation | ServerOperation
ErrorCode = Literal[{quoted_union(error_codes, ", ")}]
ErrorCategory = Literal[{quoted_union(error_categories, ", ")}]


class ProtocolEnvelope(TypedDict):
    version: Literal["{version}"]
    messageId: str
    requestId: NotRequired[str | None]
    operation: Operation
    sequence: int
    timestamp: str
    correlationId: str
    payload: dict[str, object]


class ProtocolError(TypedDict):
    code: ErrorCode
    category: ErrorCategory
    message: str
    retryable: bool
    correlationId: str
    details: NotRequired[dict[str, str | int | float | bool | None]]
'''

    typescript = f"""// Generated by tools/generate_protocol_models.py; do not edit.
export const PROTOCOL_VERSION = {json.dumps(version)} as const;
export const CLIENT_OPERATIONS = {json.dumps(client_operations)} as const;
export const SERVER_OPERATIONS = {json.dumps(server_operations)} as const;
export const ERROR_CODES = {json.dumps(error_codes)} as const;
export const ERROR_CATEGORIES = {json.dumps(error_categories)} as const;

export type ClientOperation = (typeof CLIENT_OPERATIONS)[number];
export type ServerOperation = (typeof SERVER_OPERATIONS)[number];
export type Operation = ClientOperation | ServerOperation;
export type ErrorCode = (typeof ERROR_CODES)[number];
export type ErrorCategory = (typeof ERROR_CATEGORIES)[number];

export interface ProtocolEnvelope {{
  readonly version: typeof PROTOCOL_VERSION;
  readonly messageId: string;
  readonly requestId?: string | null;
  readonly operation: Operation;
  readonly sequence: number;
  readonly timestamp: string;
  readonly correlationId: string;
  readonly payload: Readonly<Record<string, unknown>>;
}}

export interface ProtocolError {{
  readonly code: ErrorCode;
  readonly category: ErrorCategory;
  readonly message: string;
  readonly retryable: boolean;
  readonly correlationId: string;
  readonly details?: Readonly<Record<string, string | number | boolean | null>>;
}}
"""
    return python, typescript


def sync_file(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"Generated file is stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    python, typescript = generated_contents()
    results = [
        sync_file(PYTHON_OUTPUT, python, args.check),
        sync_file(TYPESCRIPT_OUTPUT, typescript, args.check),
    ]
    for name in SCHEMA_NAMES:
        canonical = (SCHEMA_DIR / name).read_text(encoding="utf-8")
        results.append(sync_file(PACKAGED_SCHEMA_DIR / name, canonical, args.check))
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
